# Generated by Django 4.0 on 2022-05-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_user_name', models.CharField(max_length=100)),
                ('customer_password', models.CharField(max_length=100)),
                ('customer_phone_number', models.IntegerField(max_length=10)),
                ('customer_email_id', models.EmailField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity', models.IntegerField(max_length=10)),
                ('product_start_bidding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_last_date_bidding', models.DateField()),
                ('product_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SellerModel',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_phone_number', models.IntegerField(max_length=10)),
                ('seller_email_id', models.EmailField(max_length=100)),
                ('seller_address', models.CharField(max_length=100)),
            ],
        ),
    ]
