# Generated by Django 4.0 on 2022-05-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0002_bidsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home', 'Home')], default='Mobiles', max_length=100),
        ),
    ]
