# Generated by Django 4.0 on 2022-06-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0003_alter_productmodel_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='seller_id',
            field=models.IntegerField(),
        ),
    ]
